/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liang_gpio_demo_Gpio */

#ifndef _Included_com_example_liang_gpio_demo_Gpio
#define _Included_com_example_liang_gpio_demo_Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_liang_gpio_1demo_Gpio_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    nativeWriteGpio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_gpio_1demo_Gpio_nativeWriteGpio
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    nativeReadGpio
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_gpio_1demo_Gpio_nativeReadGpio
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
