/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liang_gpio_demo_Gpio */

#ifndef _Included_com_example_liang_gpio_demo_Gpio
#define _Included_com_example_liang_gpio_demo_Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    Init_GPIO
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_gpio_1demo_Gpio_Init_1GPIO
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    Set_GPIO
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_gpio_1demo_Gpio_Set_1GPIO
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    Get_GPIO
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_gpio_1demo_Gpio_Get_1GPIO
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
